"""
Configuration module for CampusVoice.
"""

from .settings import settings, Settings, get_settings, reload_settings
from .constants import (
    # Enums
    DepartmentCode,
    CategoryName,
    AuthorityType,
    ComplaintStatus,
    PriorityLevel,
    VisibilityLevel,
    Gender,
    StayType,
    StudentYear,
    VoteType,
    NotificationType,
    LLMOperationType,
    ImageVerificationStatus,
    UpdatePriority,
    UpdateVisibility,
    UpdateCategory,
    # Lists
    DEPARTMENTS,
    CATEGORIES,
    SPAM_KEYWORDS,
    VALID_YEARS,
    ALLOWED_IMAGE_MIMETYPES,
    # Dicts
    AUTHORITY_LEVELS,
    LEVEL_TO_AUTHORITY,
    VALID_STATUS_TRANSITIONS,
    PRIORITY_SCORES,
    DEFAULT_CATEGORY_ROUTING,
    ESCALATION_RULES,
    SLA_HOURS,
    ERROR_MESSAGES,
    SUCCESS_MESSAGES,
    ERROR_CODES,
    HTTP_STATUS,
    CACHE_KEY_TEMPLATES,
    CACHE_TTL,
    WS_EVENTS,
    DATE_FORMATS,
    RATE_LIMIT_KEYS,
    SPAM_DETECTION_THRESHOLDS,
    THUMBNAIL_SIZES,
    # Constants
    VOTE_IMPACT_MULTIPLIER,
    PRIORITY_AUTO_ESCALATE_THRESHOLD,
    MIN_COMPLAINT_LENGTH,
    MAX_COMPLAINT_LENGTH,
    MAX_UPDATE_LENGTH,
    MIN_UPDATE_LENGTH,
    UPDATE_EXPIRY_DAYS,
    DEFAULT_PAGE_SIZE,
    MAX_PAGE_SIZE,
    MIN_PAGE_SIZE,
    AUTO_ESCALATE_HOURS,
    MAX_IMAGE_WIDTH,
    MAX_IMAGE_HEIGHT,
    IMAGE_QUALITY,
    MAX_IMAGE_SIZE_MB,
    SESSION_TIMEOUT_MINUTES,
    TOKEN_EXPIRATION_SECONDS,
    CROSS_DEPARTMENT_AUTHORITY,
    # Patterns
    EMAIL_PATTERN,
    ROLL_NO_PATTERN,
    PHONE_PATTERN,
    PASSWORD_PATTERN,
    # Helper Functions
    get_priority_from_score,
    is_valid_status_transition,
    is_valid_year,
    get_authority_level,
    can_escalate_to,
)

__all__ = [
    # Settings
    "settings",
    "Settings",
    "get_settings",
    "reload_settings",
    # Enums
    "DepartmentCode",
    "CategoryName",
    "AuthorityType",
    "ComplaintStatus",
    "PriorityLevel",
    "VisibilityLevel",
    "Gender",
    "StayType",
    "StudentYear",
    "VoteType",
    "NotificationType",
    "LLMOperationType",
    "ImageVerificationStatus",
    "UpdatePriority",
    "UpdateVisibility",
    "UpdateCategory",
    # Lists
    "DEPARTMENTS",
    "CATEGORIES",
    "SPAM_KEYWORDS",
    "VALID_YEARS",
    "ALLOWED_IMAGE_MIMETYPES",
    # Dicts
    "AUTHORITY_LEVELS",
    "LEVEL_TO_AUTHORITY",
    "VALID_STATUS_TRANSITIONS",
    "PRIORITY_SCORES",
    "DEFAULT_CATEGORY_ROUTING",
    "ESCALATION_RULES",
    "SLA_HOURS",
    "ERROR_MESSAGES",
    "SUCCESS_MESSAGES",
    "ERROR_CODES",
    "HTTP_STATUS",
    "CACHE_KEY_TEMPLATES",
    "CACHE_TTL",
    "WS_EVENTS",
    "DATE_FORMATS",
    "RATE_LIMIT_KEYS",
    "SPAM_DETECTION_THRESHOLDS",
    "THUMBNAIL_SIZES",
    # Constants
    "VOTE_IMPACT_MULTIPLIER",
    "PRIORITY_AUTO_ESCALATE_THRESHOLD",
    "MIN_COMPLAINT_LENGTH",
    "MAX_COMPLAINT_LENGTH",
    "MAX_UPDATE_LENGTH",
    "MIN_UPDATE_LENGTH",
    "UPDATE_EXPIRY_DAYS",
    "DEFAULT_PAGE_SIZE",
    "MAX_PAGE_SIZE",
    "MIN_PAGE_SIZE",
    "AUTO_ESCALATE_HOURS",
    "MAX_IMAGE_WIDTH",
    "MAX_IMAGE_HEIGHT",
    "IMAGE_QUALITY",
    "MAX_IMAGE_SIZE_MB",
    "SESSION_TIMEOUT_MINUTES",
    "TOKEN_EXPIRATION_SECONDS",
    "CROSS_DEPARTMENT_AUTHORITY",
    # Patterns
    "EMAIL_PATTERN",
    "ROLL_NO_PATTERN",
    "PHONE_PATTERN",
    "PASSWORD_PATTERN",
    # Helper Functions
    "get_priority_from_score",
    "is_valid_status_transition",
    "is_valid_year",
    "get_authority_level",
    "can_escalate_to",
]
